### ISSUE TITLE
ModuleNotFoundError: No module named 'constants'

### ISSUE THREAD

**Issue by baryluk** [thelocomotion/GloriousProtonManager#4]
```
$ python3 -m GloriousProtonManager
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 187, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib/python3.10/runpy.py", line 146, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/usr/lib/python3.10/runpy.py", line 110, in _get_module_details
    __import__(pkg_name)
  File "/home/user/.local/lib/python3.10/site-packages/GloriousProtonManager/__init__.py", line 1, in <module>
    from .gpm import *
  File "/home/user/.local/lib/python3.10/site-packages/GloriousProtonManager/gpm.py", line 9, in <module>
    from constants import DEFAULT_DIR, PROTON_GE_LATEST, PROTON_GE_RELEASES
ModuleNotFoundError: No module named 'constants'
```

```
$ pip3 list | grep -Ei 'glori|tk|simple'
GloriousProtonManager 0.31
PySimpleGUI           4.60.1
PySimpleSOAP          1.16.2
simplejson            3.17.6
TkinterTreectrl       2.0
ttkthemes             3.2.2
```

**Comment by thelocomotion** [comment]
Hi @baryluk ,

Please follow the installation steps. 'constants' is a file holding some variables needed for the main script (gpm.py) to run.

Let me know how it goes.

**Comment by baryluk** [comment]
Well, now it is broken in another way:

```
user@debian:~$ pip3 install GloriousProtonManager
Defaulting to user installation because normal site-packages is not writeable
Collecting GloriousProtonManager
  Downloading GloriousProtonManager-0.41-py3-none-any.whl (15 kB)
Collecting PySimpleGUI
  Downloading PySimpleGUI-4.60.1-py3-none-any.whl (509 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 509.3/509.3 kB 27.5 MB/s eta 0:00:00
Requirement already satisfied: requests in /usr/lib/python3/dist-packages (from GloriousProtonManager) (2.27.1)
Installing collected packages: PySimpleGUI, GloriousProtonManager
  WARNING: The script gpm is installed in '/home/user/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
Successfully installed GloriousProtonManager-0.41 PySimpleGUI-4.60.1
user@debian:~$ cd /home/user/.local/bin
user@debian:~/.local/bin$ ./gpm 
Traceback (most recent call last):
  File "/home/user/.local/bin/./gpm", line 5, in <module>
    from bin.gpm import main
ModuleNotFoundError: No module named 'bin'
user@debian:~/.local/bin$ python3 -m GloriousProtonManager
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 187, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib/python3.10/runpy.py", line 146, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/usr/lib/python3.10/runpy.py", line 110, in _get_module_details
    __import__(pkg_name)
  File "/home/user/.local/lib/python3.10/site-packages/GloriousProtonManager/__init__.py", line 5, in <module>
    from bin.gpm import *
ModuleNotFoundError: No module named 'bin'
```

**Comment by thelocomotion** [comment]
Version 0.39 is working fine, sorry about that. I've been trying to change the structure of the app a little and it's causing some issues. I removed the broken releases off pypi.

`pip3 install GloriousProtonManager==0.39`

**Comment by baryluk** [comment]
No problem. Packages and modules in python are hard.

`user@debian:~/.local/lib/python3.10/site-packages/GloriousProtonManager$ python3 gpm.py ` works

but `python3 -m GloriousProtonManager` still shows error as in the first post.

This patch fixes the `python3 -m GloriousProtonManager`

```
-from .constants import DEFAULT_DIR, PROTON_GE_LATEST, PROTON_GE_RELEASES
-from .constants import BUTTON_COLOR
+from .constants import DEFAULT_DIR, PROTON_GE_LATEST, PROTON_GE_RELEASES
+from .constants import BUTTON_COLOR
```

but it breaks `python3 gpm.py`:

```
Traceback (most recent call last):
  File "/home/user/.local/lib/python3.10/site-packages/GloriousProtonManager/gpm.py", line 9, in <module>
    from .constants import DEFAULT_DIR, PROTON_GE_LATEST, PROTON_GE_RELEASES
ImportError: attempted relative import with no known parent package
```

**Comment by thelocomotion** [comment]
At the moment I'm trying to understand how __main__ and __init__ interact with each other. My idea is to have all files living in the same src/GloriousProtonManager directory, even though I'm also considering having a lib/ and bin/ directories as well.

I've been playing for like 10 hours in the last 2 days to get that working to no avail. I believe that I came across the fix you mentioned (which funnily enough breaks something else) one of those 200 times I tried moving things around. 

I also spent some time looking at other projects to see how they were doing what I'm trying to do and even tho I'm refactoring things the same way.. My app cannot be run from .local/bin/gpm and it breaks. There is clearly something I'm missing out.

I'll post an update once I figure this out.

**Comment by thelocomotion** [comment]
@baryluk `python3 -m GloriousProtonManager` is now working. I managed to reconfigure the structure of the app a bit and finally the package added to .local/bin works. Some bugs were introduced after these changes which I've added to the Know Bugs section in the README.

**Comment by baryluk** [comment]
@thelocomotion that works.

Note that `~/.local/bin/` is not a part of a `PATH` in most distros and shells. It needs to be added manually. Don't mention `PATH`, just say to launch via `~/.local/bin/GloriousProtonManager` Most people will not how to edit their `PATH`.
